(function(){'use strict';
const START='İstasyon Caddesi 241 Sokak No:6, Karaman, Türkiye';
const C={'İstasyon Caddesi 241 Sokak No:6, Karaman, Türkiye':'37.18195,33.22120','Karaman Kalesi, Karaman':'37.182098,33.205250','Aktekke Camii, Karaman':'37.18145,33.21785','Yunus Emre Camii ve Türbesi, Karaman':'37.18240,33.22040','Tartan Konağı, Karaman':'37.18120,33.21830','Yerköprü Şelalesi, Hadim, Konya':'37.02867,32.70108','Yerköprü Şelalesi, Hadim, Konya, Türkiye':'37.02867,32.70108','Ermenek Barajı, Karaman':'36.56806,32.96778','Binbir Kilise, Madenşehri, Karaman':'37.43154,33.11749','Binbir Kilise, Madenşehri, Karaman, Türkiye':'37.43154,33.11749','Manazan Mağaraları, Karaman':'37.3380,33.1920','Taşkale Tahıl Ambarları, Karaman':'37.0050,33.4280'};
function norm(s){return(s||'').toLocaleLowerCase('tr-TR').replace(/[’']/g,"'").replace(/\s+/g,' ').trim()}
function coord(s){const n=norm(s);for(const k in C){const q=norm(k);if(n===q||n.includes(q)||q.includes(n))return C[k]}if(n.includes('yerköprü')&&n.includes('şelale'))return C['Yerköprü Şelalesi, Hadim, Konya'];if(n.includes('binbir kilise'))return C['Binbir Kilise, Madenşehri, Karaman'];return null}
function items(){return(window.__KARAMAN_ITEMS&&window.__KARAMAN_ITEMS[window.day])||[]}
function exactPlace(i){return i&&i.x&&i.x[4]}
window.mapUrl=function(place){const arr=items();let idx=arr.findIndex(it=>exactPlace(it)===place);if(idx<0)idx=arr.findIndex(it=>norm(exactPlace(it))===norm(place));let origin=START;if(idx>0)origin=exactPlace(arr[idx-1])||START;const o=coord(origin)||origin;const d=coord(place)||place;return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(o)+'&destination='+encodeURIComponent(d)+'&travelmode=driving'};
window.fullDayUrl=function(){const arr=items();const pts=[];const seen=new Set();function add(v){if(!v)return;const p=coord(v)||v;if(!seen.has(p)){seen.add(p);pts.push(p)}}add(START);arr.forEach(it=>add(exactPlace(it)));if(pts.length<2)return'#';const origin=pts.shift(),destination=pts.pop(),wps=pts.join('|');return'https://www.google.com/maps/dir/?api=1&origin='+encodeURIComponent(origin)+'&destination='+encodeURIComponent(destination)+(wps?'&waypoints='+encodeURIComponent(wps):'')+'&travelmode=driving'};
})();