const CACHE='karaman-gezi-v13';
const ASSETS=['./','./index.html','./manifest.json','./icon.svg','./override.js','./route-fix.js','./route-final.js','./final-fix.js'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url);
 if(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/')){
  event.respondWith(fetch(event.request,{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error('network');const text=await r.text();const patch=`<script>(function(){const K='karaman-v12-day',saved=localStorage.getItem(K);function same(){document.querySelectorAll('.stop').forEach(c=>{const m=c.querySelectorAll('.meta'),a=c.querySelector('a.route');if(!a||m.length<2)return;const p=(m[1].textContent||'').trim().split(' → ');if(p.length===2&&p[0].trim()===p[1].trim()){a.removeAttribute('href');a.removeAttribute('target');a.textContent='📍 Aynı konum — rota gerekmiyor';a.style.background='#66717c';a.onclick=e=>e.preventDefault()}})}function init(){if(typeof window.setDay==='function'&&!window.__dayPersist){const f=window.setDay;window.setDay=function(d){localStorage.setItem(K,d);return f(d)};window.__dayPersist=true;if(saved&&saved!==document.querySelector('.days button.active')?.textContent?.trim())window.setDay(saved)}same()}new MutationObserver(same).observe(document.body,{childList:true,subtree:true});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init()})();</script></body>`;const enhanced=text.replace('</body>',patch);const response=new Response(enhanced,{status:r.status,statusText:r.statusText,headers:r.headers});caches.open(CACHE).then(c=>c.put(event.request,response.clone()));return response}).catch(()=>caches.match(event.request).then(r=>r||caches.match('./index.html'))));return;
 }
 event.respondWith(caches.match(event.request).then(r=>r||fetch(event.request).then(x=>{const copy=x.clone();caches.open(CACHE).then(c=>c.put(event.request,copy));return x}).catch(()=>caches.match('./index.html'))));
});